### ISSUE TITLE
please add a api call to list all provisioned instances

### ISSUE THREAD

**Issue by slieberth** [rtbrick/bngblaster-controller#7]
Hi Christian,
please add a api call to list all provisioned instances
e.g.
GET /instances
regards Stefan

**Comment by GIC-de** [comment]
Fixed with `0.1.0`!

**Comment by slieberth** [comment]
Helle Christian,
thanks for implementing, 
I am currently travelling; I will test this end of June.

best regards Stefan

 

 

From: Christian Giese ***@***.***>
Reply to: rtbrick/bngblaster-controller ***@***.***>
Date: Monday, 3. June 2024 at 21:50
To: rtbrick/bngblaster-controller ***@***.***>
Cc: Stefan Lieberth ***@***.***>, Author ***@***.***>
Subject: Re: [rtbrick/bngblaster-controller] please add a api call to list all provisioned instances (Issue #7)

 

Fixed with 0.1.0!
